image: ubuntu
platform: Any CPU

environment:
  CODACY_PROJECT_TOKEN:
    secure: U8hbHMmPG+5h+ngiCFyEtwtchNxuUD35c09OGZQjiqlEdyhNm7b5bSp5AgtKNspF
  CC_TEST_REPORTER_ID:
    secure: rLP9/TZs394tk4MPEfD1zQ+jUTmrhor6Ce/xBuCoFPF+aiOaiaUGXWpgS12imPu9IgpP86BkadDAXA137CXe9zriOQnoU64iHTnwPNhJLy4=

stack: "node 14"

install:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # install modules
  - sh: npm ci
  - sh: npm install -g mocha c8

before_test:
  # Download codeclimate test report
  - sh: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./codeclimate-test-reporter
  - sh: chmod +x ./codeclimate-test-reporter

test_script:
  - npm run build
  - c8 --reporter=lcov mocha --timeout 30000

after_test:
  # Send test result to codeclimate
  - sh: ./codeclimate-test-reporter before-build
  - sh: ./codeclimate-test-reporter after-build -t lcov --exit-code $?
  # Send test result to Codacy
  - sh: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./coverage/lcov.info

# Don't actually build.
build: off
